Feat/translation-bubble
satuju-tech/Satuju-iOS pull request #10
Opened 2021-10-29 09:09 UTC by mrifkiw

2021-10-30 13:39 UTC, yrojx requested changes
3 files of Bubble Chat can be into 1 file and keep the code less. The keyword is "conditional modifiers"

2021-11-01 06:49 UTC, mrifkiw commented
Bubble chat file have been refactor into one file, please check my last push.

2021-11-01 08:13 UTC, yrojx requested changes

2021-11-01 08:13 UTC, yrojx commented on Satuju/Module/TranslationBubble/View/TranslationBubble.swift
> +        .flipsForRightToLeftLayoutDirection(false)
unused function

2021-11-01 08:13 UTC, yrojx commented on Satuju/Module/TranslationBubble/View/TranslationBubble.swift
> +                .environment(\.layoutDirection, .leftToRight)
can be just once declaration

2021-11-01 08:28 UTC, yrojx approved these changes

2021-11-01 08:28 UTC, merged