Menu Process Done
satuju-tech/Satuju-iOS pull request #24
Opened 2021-11-04 08:05 UTC by GedePrama

Check this backlog:
- Menu Process
- Text to Voice Translation
- Replay Button Logic

2021-11-04 08:10 UTC, mrifkiw commented on Satuju/Helper/ViewHasScrollEnabled.swift
> +}
penamaan helpernya udah bener gak nih can @yrojx ?

2021-11-06 03:46 UTC, yrojx commented on Satuju/Helper/ViewHasScrollEnabled.swift
> +}
View+hasScrollEnabled

2021-11-06 03:47 UTC, yrojx requested changes

2021-11-06 03:47 UTC, yrojx commented on Satuju/Helper/ViewHasScrollEnabled.swift
> +//  ViewHasScrollEnabled.swift
View+hasScrollEnabled

2021-11-06 03:47 UTC, yrojx commented
ntr kalo udah, aku resolve-in konfliknya

2021-11-06 08:22 UTC, closed without merging