Feat/soundwave
satuju-tech/Satuju-iOS pull request #27
Opened 2021-11-05 08:19 UTC by mrifkiw

2021-11-05 08:36 UTC, yrojx requested changes

2021-11-05 08:36 UTC, yrojx commented on Satuju/Module/Soundwave/SoundWaveView.swift
> +var rightGradientColor: Color = Color(red: 20/255, green: 145/255, blue: 156/255)
space after operator

2021-11-05 08:59 UTC, rahmanarifofficial approved these changes

2021-11-05 09:00 UTC, rahmanarifofficial approved these changes

2021-11-06 03:45 UTC, yrojx approved these changes

2021-11-06 03:45 UTC, merged